stages:
  - dockerized
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  TF_INPUT: "false"
  TF_IN_AUTOMATION: "true"

before_script:
  - echo "Starte Pipeline..."

build:
  stage: dockerized
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$TF_VAR_docker_image_name .
    - docker push $DOCKER_REGISTRY/$TF_VAR_docker_image_name
  only:
    - main
  tags:
    - mmbbs3


deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  script:
    - terraform init -reconfigure
    - terraform validate
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan
  only:
    - main
  environment:
    name: production
  tags:
    - mmbbs3
