stages:
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "Starte Pipeline..."

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
  only:
    - main
  tags:
    - mmbbs3

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main
  dependencies:
    - build
  tags:
    - mmbbs3

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint: ['']
  script:
    - terraform init
    - terraform apply -auto-approve
  only:
    - main
  dependencies:
    - push
  environment:
    name: production
  tags:
    - mmbbs3
